#Display robot face
print("##########")
eye = input()
print("#  #  #  #")
print("#        #")
print("##########")
print("   ###    ")
print("##########")
print("#        #")
print("#        #")
print("#        #")
print("#        #")
print("#        #")
print("##########")
print("   ###    ")
print("   ###    ")
print("   ###    ")